# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-09-05 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180901_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 9, 5, 18, 52, 57, 999548, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
